language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '10'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && branch == master && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: "S7Zy4iECBNI06ynjAI1JwFy3JWJN55L+AX2h5lGw0zpnrHHk8smvcBQKmBp5Hmz25KL/BoMogbNwOWMhOGBFXJtoKgTow+2mYTer22zOviAsCq9jENicL/5Aq/EVxRgzOTOvJ5EObKQyJWVNja05v5VimcQbxMTdEfAMF+B2CNpTePSP9RO/1UZQcIp21YJRApdHXEBYl8WiAvWZW6DVb+GleUTtnPf2O9HjuUcPireX6ezPgtb5WoVI7PqpFWb4UJs5ZS3lMBPWQKCU20+4hdndsHlVbh1O5c0Qpb5pIQrPQOz6HOEyT6oRg0XgmUT8Vb85UVrIK755FbMQOS/kOroGeIX7Dxly5PSE3RIFtbqZuko1CqA37jIIVB/qV9T+SIZ3xouW/OBDVmMqJD1as2MCxTiiYUaHgrY7U70ViFAAzIQgRkjfJN7cXxo1z1ZpvUby0oFBtALLThoAUKmQ/6LEWjG2V3QSt/MV+z/IuW31gQ2hN/iQfvU0mhBQWMxKhACqb3RcMB0kd9S3f24Z6dt2L9Jkl/+WhxrT9b3clxzmcyTLXXuz95ovOEZAwXyx0jnTJjM1P5x4+Fp5M9juQZ+EQHO28nGdT7XCljGjUq8wIwp/njYL5VJabiR3pDnTzZevi7louvEGPHX7NSwYE5G/SH9jAZU09OkNEub2rCo="
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
